### ISSUE TITLE
Creating a rock

### ISSUE THREAD

**Issue by LordNoteworthy** [ReFreezed/DumbLuaParser#1]
Hey ReFreezed,

Pretty happy to stumble upon your project, I hope you keep maintaining it :)

Will be interesting adding your package into luarock, so we can easily consume it.

I can open a PR including the spec, but some steps shall be done by you like creating an account in luarocks server and also tagging the release.

Here is how: https://github.com/luarocks/luarocks/wiki/Creating-a-rock

Let me know what you think.

**Comment by ReFreezed** [comment]
Hello. I've now added the library to LuaRocks. (https://luarocks.org/modules/refreezed/dumbluaparser)

I don't really use LuaRocks myself so let me know if there are any problems.
